# Generated by Django 4.2 on 2026-03-04 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('cedula', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_verificado', models.BooleanField(default=False)),
                ('rol', models.IntegerField(blank=True, null=True)),
                ('fecha_visita', models.DateField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2, null=True)),
                ('rol_externo', models.CharField(blank=True, max_length=255, null=True)),
                ('genero', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('codigo_vigilante', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_usuario', models.CharField(choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_registrados', to='myApp.usuario')),
            ],
        ),
    ]
