# Generated by Django 6.0.3 on 2026-04-20 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(blank=True, max_length=60, null=True)),
                ('cedula', models.CharField(max_length=14, unique=True)),
                ('genero', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_usuario', models.CharField(blank=True, choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo')], max_length=10, null=True)),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_vigilante', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_visita', models.DateField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2, null=True)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('vigilante', 'Vigilante'), ('persona', 'Persona Registrada')], default='persona', max_length=20)),
                ('subrol', models.CharField(blank=True, choices=[('oficinas', 'Oficinas'), ('enfermeria', 'Enfermería'), ('parqueadero', 'Parqueadero'), ('visitantes', 'Visitantes'), ('acudientes', 'Acudientes'), ('docentes', 'Docentes'), ('estudiantes', 'Estudiantes'), ('personal', 'Personal'), ('vigilantes', 'Vigilantes')], max_length=30, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('telefono_verificado', models.BooleanField(default=False)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_registrados', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='computador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Computador',
                'verbose_name_plural': 'Computadores',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Salida')], max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('trae_vehiculo', models.BooleanField(default=False)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('trae_pc', models.BooleanField(default=False)),
                ('serial_pc', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_registrados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
    ]
